name: "Main"

on:
  push:
    branches:
      - "main"
    paths:
      - "lib"
      - ".github/workflows/*"

jobs:
  Main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.9.0
          registry-url: "https://registry.npmjs.org"
          scope: "@hermaeusmora"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Ci
        run: npm ci

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
