name: "Main"

on:
  push:
    branches:
      - "main"
    paths:
      - "lib"

jobs:
  Main:
    name: "Main"
    runs-on: "ubuntu-latest"
    steps:
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.9.0
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}